model_cfg:
  _target_: edm.diffusion.DenoiserConfig
  sigma_data: 0.5

  sigma_offset_noise: 0.1
  noise_previous_obs: true
  upsampling_factor: null
  inner_model:
    _target_: models.diffusion.InnerModelConfig
    img_channels: 3
    num_actions: ${env.num_actions}
    num_steps_conditioning: 4
    cond_channels: 2048
    depths:
    - 2
    - 2
    - 2
    - 2
    channels:
    - 128
    - 256
    - 512
    - 1024
    attn_depths:
    - 0
    - 0
    - 1
    - 1

sigma_distribution: # log normal distribution for sigma during training
    _target_: models.diffusion.SigmaDistributionConfig
    loc: -1.2
    scale: 1.2
    sigma_min: 2e-3
    sigma_max: 20   
    
training:
  num_autoregressive_steps: 4
  start_after_epochs: 0
  steps_first_epoch: 400
  steps_per_epoch: 400
  sample_weights: null
  batch_size: 64
  grad_acc_steps: 2
  lr_warmup_steps: 100
  max_grad_norm: 10.0

  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
    eps: 1e-8
  

