defaults:
  - _self_
  - env: doom
  - diffusion_model: doom_DiT


wandb:
  project: diffusion-for-simulation-doom
  entity: diffusion-for-simulation
  name: ${common.run_name}
  group: null
  tags: null
  notes: null

diffusion:
  learn_sigma: False

pretrained_weights_url: null

initialization:
  path_to_ckpt: null

experiment_name: "" # Should be set through CLI
common:
  seed: null
  project_storage_base_path: /scratch/gs4288/shared/diffusion_for_simulation
  run_name: ${now:%Y.%m.%d}T${now:%H-%M}_${experiment_name}
  run_dir: ${common.project_storage_base_path}/runs/${common.run_name}

checkpointing:
  save_diffusion_model_every: 5
  num_to_keep: 11  # number of checkpoints to keep, use null to disable


static_dataset:
  path: ${env.data_path}
  ignore_sample_weights: True

training:
  should: True
  num_workers_data_loaders: 8

evaluation:
  should: True
  every: 5

hydra:
  run:
    dir: ${common.run_dir}
