defaults:
  - _self_
  - env: doom
  - diffusion_model: doom_DiT


hydra:
  job:
    chdir: True

wandb:
  project: diffusion-for-simulation-doom
  entity: diffusion-for-simulation
  name: null
  group: null
  tags: null
  notes: null

# pretrained_weights:
#   url: https://dl.fbaipublicfiles.com/DiT/models/DiT-XL-2-256x256.pt
#   save_path: ${common.project_storage_base_path}/pretrained_weights/
pretrained_weights: null

initialization:
  path_to_ckpt: null

common:
  devices: 0  # int, list of int, cpu, or all 
  seed: null
  project_storage_base_path: /scratch/gs4288/shared/diffusion_for_simulation

checkpointing:
  save_path: ${common.project_storage_base_path}/checkpoints/
  save_diffusion_model_every: 5
  num_to_keep: 11  # number of checkpoints to keep, use null to disable


static_dataset:
  path: ${env.data_path}
  ignore_sample_weights: True

training:
  should: True
  num_workers_data_loaders: 0

evaluation:
  should: False
  every: 20


