defaults:
  - _self_
  - env: doom
  - diffusion_model: DiT_B_4_cross_attn

wandb:
  mode: online # Logs to wandb. To disable, set to "disabled"
  project: diffusion-for-simulation-doom
  entity: diffusion-for-simulation
  name: ${common.run_name}
  group: null
  tags: null
  notes: null

diffusion:
  learn_sigma: False
  num_sampling_steps: 8

pretrained_weights_url: null

initialization:
  path_to_ckpt: null

experiment_name: "" # Should be set through CLI
common:
  seed: null
  project_storage_base_path: /scratch/gs4288/shared/diffusion_for_simulation
  run_name: ${now:%Y.%m.%d}T${now:%H-%M}_${experiment_name}
  run_dir: ${common.project_storage_base_path}/runs/${common.run_name}

checkpointing:
  save_diffusion_model_every: 5
  num_to_keep: 11  # number of checkpoints to keep, use null to disable


static_dataset:
  path: ${env.data_path_latent}
  ignore_sample_weights: True
  guarantee_full_seqs: True
  image_resolution: 256

training:
  should: True
  epoch_size: 256000
  num_epochs: 1000000
  num_workers_data_loaders: 8

evaluation:
  should: True
  sub_sample_rate: 5
  every: 1

inference:
  should: True
  every: 5
  episode_path: ${env.data_path_original}/test/episode_0.pt
  num_generated_frames: 200
  sampling_algorithm: DDIM
  vae_path: ${common.project_storage_base_path}/vae/trained_vae_decoder.pth
  vae_batch_size: 256
  generation_mode: ["teacher_forcing", "auto_regressive"]
  video_fps: 15

debug: False 

hydra:
  run:
    dir: ${common.run_dir}
