defaults:
  - _self_
  - env: doom
  - diffusion_model: DiT_VG


wandb:
  do_log: False
  project: 
  entity: 
  name: ${common.run_name}

diffusion:
  learn_sigma: False

pretrained_weights: null

initialization:
  path_to_ckpt: null

experiment_name: "" # Should be set through CLI
common:
  devices: 0  # int, list of int, cpu, or all
  seed: null
  project_storage_base_path: "" # Set this.
  run_name: ${now:%Y.%m.%d}T${now:%H-%M}_${experiment_name}
  run_dir: ${common.project_storage_base_path}/runs/${common.run_name}

checkpointing:
  save_diffusion_model_every: 1
  num_to_keep: null  # Number of checkpoints to keep, use null to disable.

static_dataset:
  path: ${env.data_path}
  ignore_sample_weights: True
  guarantee_full_seqs: True

training:
  should: True
  num_workers_data_loaders: 8

evaluation:
  should: True
  subsample_rate: 5
  every: 1
  max_num_episodes: 1000000

inference:
  should: True
  subsample_rate: 100000
  every: 1
  num_sampling_steps: 250
  vae_path: "" # Set this.
  num_log_wandb: 20
  max_num_episodes: 1000000

hydra:
  run:
    dir: ${common.run_dir}

debug: False