model:
  _target_: src.models.DiT_VG.DiT
  num_actions: ${env.num_actions}
  num_conditioning_steps: 7
  input_size: 32
  patch_size: 4
  in_channels: 4
  hidden_size: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256
  use_frame_embedding: True
  use_action_embedding: True
  learn_sigma: ${diffusion.learn_sigma}
  stacked: False

training:
  train_batch_size: 128
  eval_batch_size: 128
  steps_per_epoch: 2000
  num_epochs: 1000000
  lr_warmup_steps: 100

  optimizer:
    base_lr: 7.8125e-7 # Double scaling of DiT.
    scale_lr: True
