model:
  _target_: src.models.DiT_cross_attn.DiT
  time_frequency_embedding_size: 256
  num_actions: ${env.num_actions}
  input_size: 32
  in_channels: 4
  mlp_ratio: 4.0
  patch_size: 2
  hidden_size: 1152
  depth: 28
  num_heads: 16
  num_conditioning_steps: 32
  learn_sigma: ${diffusion.learn_sigma}
  separate_cross_attn: True
  share_patch_embed: True

training:
  train_batch_size: 8
  eval_batch_size: 8
  lr_warmup_steps: 100

  optimizer:
    # base_lr: 3.90625e-7 # same scaling as dit
    base_lr: 7.8125e-7 # double scaling of dit
    # base_lr: 1.5625e-06 # 4x scale of dit
    
    scale_lr: True
  

