model:
  _target_: src.models.DiT_cross_attn.DiT
  time_frequency_embedding_size: 256
  num_actions: ${env.num_actions}
  input_size: 32
  in_channels: 4
  mlp_ratio: 4.0
  patch_size: 4
  hidden_size: 384
  depth: 12
  num_heads: 6
  num_conditioning_steps: 32
  learn_sigma: ${diffusion.learn_sigma}
  separate_cross_attn: True
  share_patch_embed: True

training:
  train_batch_size: 256
  eval_batch_size: 512
  lr_warmup_steps: 100

  optimizer:
    base_lr: 8.8388e-6
    scale_lr: True
  

