model:
  _target_: models.DiT.DiT
  num_actions: ...
  num_conditioning_steps: 2000
  input_size: 32
  patch_size: 2
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256

    
training:
  batch_size: 64
  steps_per_epoch: 400
  lr_warmup_steps: 100


  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
    eps: 1e-8
  

