model:
  _target_: models.DiT.DiT
  num_actions: ...
  num_conditioning_steps: 300
  input_size: 32
  patch_size: 4
  in_channels: 4
  hidden_size: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256


training:
  batch_size: 32
  steps_per_epoch: 50
  num_epochs: 1600
  lr_warmup_steps: 100


  optimizer:
    lr: 1e-4
    weight_decay: 0.0
    eps: 1e-8
  

