model:
  _target_: src.models.DiT.DiT
  num_actions: ${env.num_actions}
  num_conditioning_steps: 8
  input_size: 32
  patch_size: 2
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256
  learn_sigma: ${diffusion.learn_sigma}




training:
  train_batch_size: 128
  eval_batch_size: 128
  steps_per_epoch: 500
  num_epochs: 1000000
  lr_warmup_steps: 100


  optimizer:
    # base_lr: 3.90625e-7 # same scaling as dit
    base_lr: 1e-5
    # scale_lr: True
    scale_lr: False
  

