model:
  _target_: src.models.DiT.DiT
  num_actions: ${env.num_actions}
  num_conditioning_steps: 8
  input_size: 32
  patch_size: 4
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256
  learn_sigma: ${diffusion.learn_sigma}


training:
  batch_size: 64
  steps_per_epoch: 50
  num_epochs: 1600
  lr_warmup_steps: 100


  optimizer:
    lr: 1e-5
    weight_decay: 0.0
    eps: 1e-8
  

