model:
  _target_: src.models.VDA.VDA
  num_actions: ${env.num_actions}
  num_conditioning_steps: 3
  input_size: 32
  patch_size: 2
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  time_frequency_embedding_size: 256
  use_frame_embedding: True
  use_action_embedding: True
  learn_sigma: ${diffusion.learn_sigma}
  stacked: False

training:
  train_batch_size: 16
  eval_batch_size: 16
  steps_per_epoch: 2000
  num_epochs: 1000000
  lr_warmup_steps: 100

  optimizer:
    # base_lr: 3.90625e-7 # same scaling as dit
    base_lr: 7.8125e-7 # double scaling of dit
    scale_lr: True
